# Name: PREETHA S
# USN: 21BTRCL078
# Experiment 3
# K-Nearest Neighbors using IRIS dataset
# 13-09-2023

In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
# Setup
import numpy as np

from sklearn import datasets
from sklearn import neighbors

In [3]:
iris = datasets.load_iris()
print(iris.target.shape)
print(iris.target)
print(iris.target_names)


(150,)
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
['setosa' 'versicolor' 'virginica']


In [4]:
from sklearn.model_selection import train_test_split
X, y = iris.data, iris.target

x_train,x_test,y_train,y_test= train_test_split(X,y,test_size=0.3)

In [5]:
knn1 = neighbors.KNeighborsClassifier(n_neighbors=5)
knn1.fit(x_train, y_train)
y_pred= knn1.predict(x_test)

In [6]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
cm=confusion_matrix(y_test,y_pred)
acc=accuracy_score(y_test,y_pred)
print(cm)
print(acc)

[[15  0  0]
 [ 0 16  2]
 [ 0  0 12]]
0.9555555555555556


In [7]:
result = knn1.predict([[3, 5, 4, 2],])

print(iris.target_names[result])

['versicolor']


In [8]:
knn1.predict_proba([[3, 5, 4, 2],])

array([[0. , 0.8, 0.2]])